### ISSUE TITLE
Password is written even if there's no password

### ISSUE THREAD

**Issue by Elleymenta** [Youmy001/apine-framework#17]
In "alone" installation, a password is written in [] even if no password is written.

**Comment by Youmy001** [comment]
I took a look at every password in the installation process and I did not find any bug. However, I found that the line for the password of the database is shown on the confirmation page even if the password is empty. It is shown so that he knows that he did not type a password for the database.

The confirmation page shows the value of all the fields the user saw during the configuration process.
